CREATE USER stellar WITH SUPERUSER PASSWORD 'password';
CREATE DATABASE coredb;
CREATE DATABASE horizondb;
GRANT ALL PRIVILEGES ON DATABASE coredb TO stellar;
GRANT ALL PRIVILEGES ON DATABASE horizondb TO stellar;
