#! /usr/bin/env bash
set -e

export STELLAR_HOME="/opt/stellar"
export COREHOME="$STELLAR_HOME/core"
export HZHOME="$STELLAR_HOME/horizon"

function main() {
	echo ""
	echo "Starting Stellar Node"
	echo ""

	CORE_CONFIG = "/opt/stellar/stellar.cfg"
	HORIZ_ENV = "/opt/stellar/horizon.env"
	if [ $TESTNET ]; then
	  CORE_CONFIG = "/opt/stellar/stellar-testnet.cfg"
		HORIZ_ENV = "/opt/stellar/horizon-testnet.env"
  fi

 	init_stellar_core
	init_horizon

	/start-core
	/start-horizon
  }

function init_stellar_core() {
	if [ -f $COREHOME/.core-initialized ]; then
		echo "core: already initialized"
		return 0
	fi

	stellar-core --newdb --conf $CORE_CONFIG

	touch .core-initialized
 }

function init_horizon() {
	if [ -f $HZHOME/.horizon-initialized ]; then
		echo "horizon: already initialized"
		return 0
	fi

	source $HORIZ_ENV
  horizon db init

	touch .horizon-initialized
 }

main $@
