#! /usr/bin/env bash
set -e

STELLAR_HOME="/opt/stellar"

export CORE_CONFIG="/opt/stellar/stellar.cfg"
export HORIZ_ENV="/opt/stellar/horizon.env"
if [ $TESTNET -gt 0 ]
then
	export CORE_CONFIG="/opt/stellar/stellar-testnet.cfg"
	export HORIZ_ENV="/opt/stellar/horizon-testnet.env"
fi

function main() {
	sleep 4

	echo ""
	echo "Starting Stellar Node"
	echo ""

	build-config /configs/stellar.cfg > /opt/stellar/stellar.cfg
	build-config /configs/horizon.env > /opt/stellar/horizon.env

	build-config /configs/stellar-testnet.cfg > /opt/stellar/stellar-testnet.cfg
	build-config /configs/horizon-testnet.env > /opt/stellar/horizon-testnet.env

 	init_stellar_core
	init_horizon

	/start-core
	/start-horizon
  }

function init_stellar_core() {
	if [ -f $STELLAR_HOME/.core-initialized ]
	then
		echo "core: already initialized"
		return 0
	fi

	stellar-core --conf $CORE_CONFIG --newdb

	touch $STELLAR_HOME/.core-initialized
 }

function init_horizon() {
	if [ -f $STELLAR_HOME/.horizon-initialized ]
	then
		echo "horizon: already initialized"
		return 0
	fi

	source $HORIZ_ENV
  horizon db init

	touch $STELLAR_HOME/.horizon-initialized
 }

echo 'starting...'
main
