#!/bin/bash
set -e

while ! psql -U stellar -c 'select 1' core &> /dev/null ; do
  echo "Waiting for core postgres to be available..."
  sleep 1
done

echo "starting core..."

exec /usr/local/bin/stellar-core --conf $CORE_CONFIG
