#! /usr/bin/env bash
set -e

STELLAR_HOME="/opt/stellar"

function main() {
	echo ""
	echo "Starting Stellar Node"
	echo ""

	CORE_CONFIG = "/opt/stellar/stellar.cfg"
	HORIZ_ENV = "/opt/stellar/horizon.env"
	if [ $TESTNET -gt 0 ]
	then
	  CORE_CONFIG = "/opt/stellar/stellar-testnet.cfg"
		HORIZ_ENV = "/opt/stellar/horizon-testnet.env"
  fi

 	init_stellar_core
	init_horizon

	/start-core
	/start-horizon
  }

function init_stellar_core() {
	if [ -f $STELLAR_HOME/.core-initialized ]
	then
		echo "core: already initialized"
		return 0
	fi

	stellar-core --newdb --conf $CORE_CONFIG

	touch $STELLAR_HOME/.core-initialized
 }

function init_horizon() {
	if [ -f $STELLAR_HOME/.horizon-initialized ]
	then
		echo "horizon: already initialized"
		return 0
	fi

	source $HORIZ_ENV
  horizon db init

	touch $STELLAR_HOME/.horizon-initialized
 }

echo 'starting...'
main
