#! /bin/bash
set -e

sleep 2

while ! stellar-core --conf /opt/stellar/core/etc/stellar-core.cfg -c info &> /dev/null ; do
  echo "Waiting for stellar-core to be available..."
  sleep 1
done

echo "starting horizon..."

source $HORIZ_ENV
exec /usr/local/bin/horizon $@
