#! /bin/bash
set -e

while ! psql -h stellarpostgres -U stellar -c 'select 1' horizondb &> /dev/null ; do
  echo "Waiting for horizondb to be available..."
  sleep 1
done

while ! stellar-core --conf $CORE_CONFIG -c info &> /dev/null ; do
  echo "Waiting for stellar-core to be available..."
  sleep 1
done

echo "starting horizon..."

source $HORIZ_ENV
exec horizon
